"""initial schema

Revision ID: 52d01d22f7e8
Revises: 
Create Date: 2026-06-13 14:43:14.546965
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d01d22f7e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('native_language', sa.String(length=64), nullable=False),
    sa.Column('target_language', sa.String(length=64), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=False),
    sa.Column('topic_category', sa.String(length=120), nullable=True),
    sa.Column('topic_description', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=30), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('selected_sources', sa.JSON(), nullable=True),
    sa.Column('adapted_content', sa.JSON(), nullable=True),
    sa.Column('script', sa.JSON(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('audio_format', sa.String(length=8), nullable=False),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcasts_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcasts_status'), ['status'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('podcast_id', sa.String(length=32), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_podcast_id'), ['podcast_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('podcast_id', sa.String(length=32), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('revision_target', sa.String(length=30), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_podcast_id'), ['podcast_id'], unique=False)

    op.create_table('exercise_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('podcast_id', sa.String(length=32), nullable=False),
    sa.Column('submission', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_attempts_podcast_id'), ['podcast_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_attempts_podcast_id'))

    op.drop_table('exercise_attempts')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_podcast_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_podcast_id'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_agent'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('podcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcasts_status'))
        batch_op.drop_index(batch_op.f('ix_podcasts_owner'))

    op.drop_table('podcasts')
    # ### end Alembic commands ###
